---
- hosts: all
  become: true
  pre_tasks:

  - name: Update CentOS servers
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: Update Ubuntu servers
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: server1
  become: true
  roles:
    - server1

- hosts: server2
  become: true
  roles:
    - server2

- hosts: server3
  become: true
  roles:
    - server3

